### ISSUE TITLE
Update for Skyrim SE changes

### ISSUE THREAD

**Issue by WrinklyNinja** [WrinklyNinja/libloadorder#36]
Skyrim SE doesn't include the official plugins in its plugins.txt, so libloadorder shouldn't either. It also currently (as of 1.2.39) loads the DLC plugins in timestamp order, which makes no sense whatsoever, so I'm in favour of just changing the hardcoded order to use the same as NMM as it's also the order that is most commonly assumed for the DLC in the original Skyrim. That order is:

```
Dawnguard.esm
Hearthfires.esm
Dragonborn.esm
```

@DuskDweller, will NMM be changing how it handles the DLC plugins' load order for Skyrim SE?

**Comment by DuskDweller** [comment]
Hi @WrinklyNinja , currently NMM doesn't manage official plugins for Skyrim SE (base game or DLCs), it will just show their "intended" loadorder in the NMM Plugins list, but it's just visual feedback, there's nothing inside NMM managing those file. 
When saving the plugin list NMM won't add any of those files to the plugins.txt file since it seems the Skyrim SE game will ignore them anyway (also the game doesn't add them when enabling plugins within the game UI).

**Comment by WrinklyNinja** [comment]
Thanks for the quick reply!
